// This file was automatically generated by VS extension Windows Machine Learning Code Generator v3
// from model file PetModel.onnx
// Warning: This file may get overwritten if you add add an onnx file with the same name

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Windows.AI.MachineLearning;
using Windows.Storage.Streams;

namespace DogOrCat.UWP.WindowsML
{

    public sealed class PetModelInput
    {
        public ImageFeatureValue data; // BitmapPixelFormat: Bgra8, BitmapAlphaMode: Premultiplied, width: 224, height: 224
    }

    public sealed class PetModelOutput
    {
        public TensorString classLabel; // shape(-1,1)
        public IList<IDictionary<string, float>> loss;
    }

    public sealed class PetModelModel
    {
        private LearningModel model;
        private LearningModelSession session;
        private LearningModelBinding binding;
        public static async Task<PetModelModel> CreateFromStreamAsync(IRandomAccessStreamReference stream)
        {
            PetModelModel learningModel = new PetModelModel();
            learningModel.model = await LearningModel.LoadFromStreamAsync(stream);
            learningModel.session = new LearningModelSession(learningModel.model);
            learningModel.binding = new LearningModelBinding(learningModel.session);
            return learningModel;
        }
        public async Task<PetModelOutput> EvaluateAsync(PetModelInput input)
        {
            binding.Bind("data", input.data);
            var result = await session.EvaluateAsync(binding, "0");
            var output = new PetModelOutput();
            output.classLabel = result.Outputs["classLabel"] as TensorString;
            output.loss = result.Outputs["loss"] as IList<IDictionary<string, float>>;
            return output;
        }
    }
}